In [3]:
import pandas as pd

In [6]:
df_books=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [7]:
def two_times(value):
  return value*2

In [9]:
#toma cada una de los valores de la fila que estan en user ratings y le aplica la funcion
#apply es mucho mas rapido que plaicar un bucle for
df_books['User Rating'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ...
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [11]:
#el Dataframe se le va crear una nueva columna llamda 'Rating_2'
df_books['Rating_2']=df_books['User Rating'].apply(lambda x:x*3)
#ahora vemos la creacion de la columna
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,14.1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,13.8
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,14.1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,14.1
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,14.4
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,14.7
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,14.1
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,14.1
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,14.1
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,14.1

In [12]:
df_books['Rating_2']=df_books['User Rating'].apply(lambda x:x*3)
df_books.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,14.1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,13.8
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,14.1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,14.1
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,14.4

In [14]:
#si quiero ocupar distintas columnas para hacer las operaciones, el apply se loo hago al DaataFrame en general 
#se coloca axis=1 porque les queremos decir que los nombres se hace referencia a la columna 1 'axis=1'
df_books.apply(lambda x:x['User Rating']*2 if x['Genre']=='Fiction' else x['User Rating'], axis=1)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,14.1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,13.8
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,14.1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,14.1
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,14.4
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,14.7
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,14.1
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,14.1
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,14.1
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,14.1